version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'oauth-connector-sdk-maintainers'
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    groups:
      # Group TypeScript and ESLint updates
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'eslint*'
          - '@typescript-eslint/*'
      # Group testing dependencies
      testing:
        patterns:
          - 'vitest*'
          - '@vitest/*'
          - 'nock'
      # Group build tools
      build:
        patterns:
          - 'tsx'
          - 'prettier'
      # Group production dependencies
      production:
        patterns:
          - '*'
        exclude-patterns:
          - 'typescript'
          - '@types/*'
          - 'eslint*'
          - 'vitest*'
          - 'tsx'
          - 'prettier'
          - 'nock'

  # Enable GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore(ci)'
